[package]
name = "zamm_yang"
version = "0.0.2"
authors = ["Amos Jun-yeung Ng <me@amos.ng>"]
edition = "2018"
description = "A basic, experimental code generator"
readme = "README.md"
repository = "https://github.com/amosjyng/yang"
license = "GPL-3.0"
keywords = ["codegen", "code-generation"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "yang"
path = "src/main.rs"

[dependencies]
clap = "^2.33.3"
path_abs = "^0.5.0"
textwrap = "^0.12.1"
zamm_yin = "^0.0.2"

[dev-dependencies]
indoc = "^1.0"
